"""Initial migration.

Revision ID: 737fd5b965af
Revises: 
Create Date: 2022-03-27 13:40:15.578219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737fd5b965af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credentials')
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_foreign_key(None, 'users', 'departments', ['department'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.create_table('user_credentials',
    sa.Column('permission', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('permission', name='user_credentials_pkey')
    )
    # ### end Alembic commands ###
